[project]
name = "advent-mojo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mojo-compiler>=0.26.1.0.dev2025122205",
]

[[tool.uv.index]]
url = "https://dl.modular.com/public/nightly/python/simple/"
default = true
